// AUTO-GENERATED by scripts/gen_sample_data.py — do not edit manually.
// Represents a realistic 5-year SIP portfolio (Jun 2021 → today) with
// ₹15,250/month across 18 diversified funds, lump-sum top-ups, and partial
// redemptions. Used as the always-present "Sample Portfolio" demo profile.

import type { Holding, Redemption } from './types'

export const SAMPLE_HOLDINGS: Omit<Holding, 'id' | 'created_at'>[] = [
  {
    "scheme_code": 120716,
    "scheme_name": "UTI Nifty 50 Index Fund - Direct Plan - Growth",
    "units": 1006.3049,
    "buy_nav": 134.1542,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 118825,
    "scheme_name": "Mirae Asset Large Cap Fund - Direct Plan - Growth",
    "units": 598.2093,
    "buy_nav": 100.2993,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 118632,
    "scheme_name": "Nippon India Large Cap Fund - Direct Plan Growth Plan - Growth Option",
    "units": 579.547,
    "buy_nav": 73.7645,
    "buy_date": "2021-09-10",
    "notes": "Sample: SIP 2021-09-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 122639,
    "scheme_name": "Parag Parikh Flexi Cap Fund - Direct Plan - Growth",
    "units": 2454.6375,
    "buy_nav": 59.0719,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 120166,
    "scheme_name": "Kotak Flexicap Fund - Growth - Direct",
    "units": 592.0783,
    "buy_nav": 72.2033,
    "buy_date": "2021-09-10",
    "notes": "Sample: SIP 2021-09-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 118955,
    "scheme_name": "HDFC Flexi Cap Fund - Growth Option - Direct Plan",
    "units": 35.781,
    "buy_nav": 1271.6246,
    "buy_date": "2022-03-10",
    "notes": "Sample: SIP 2022-03-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 119071,
    "scheme_name": "DSP Midcap Fund - Direct Plan - Growth",
    "units": 505.7048,
    "buy_nav": 118.6463,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 120403,
    "scheme_name": "Invesco India Midcap Fund - Direct Plan - Growth Option",
    "units": 291.0152,
    "buy_nav": 139.168,
    "buy_date": "2021-12-10",
    "notes": "Sample: SIP 2021-12-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 125354,
    "scheme_name": "Axis Small Cap Fund - Direct Plan - Growth",
    "units": 646.7154,
    "buy_nav": 87.2099,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 118778,
    "scheme_name": "Nippon India Small Cap Fund - Direct Plan Growth Plan - Growth Option",
    "units": 308.0059,
    "buy_nav": 133.926,
    "buy_date": "2021-11-10",
    "notes": "Sample: SIP 2021-11-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 146513,
    "scheme_name": "Nippon India Nifty Next 50 Junior BeES FoF - Direct Plan - Growth",
    "units": 2028.2057,
    "buy_nav": 19.5986,
    "buy_date": "2022-01-10",
    "notes": "Sample: SIP 2022-01-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 134813,
    "scheme_name": "Mirae Asset Aggressive Hybrid Fund - Direct Plan - Growth",
    "units": 2642.853,
    "buy_nav": 28.3784,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 131373,
    "scheme_name": "Kotak Equity Savings Fund - Direct - Growth",
    "units": 1352.4398,
    "buy_nav": 24.2063,
    "buy_date": "2021-08-10",
    "notes": "Sample: SIP 2021-08-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 145552,
    "scheme_name": "Motilal Oswal Nasdaq 100 Fund of Fund - Direct Plan Growth",
    "units": 1056.3118,
    "buy_nav": 28.4007,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 140243,
    "scheme_name": "Edelweiss Greater China Equity Off-shore Fund - Direct Plan - Growth",
    "units": 281.797,
    "buy_nav": 43.9589,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 120594,
    "scheme_name": "ICICI Prudential Technology Fund - Direct Plan - Growth",
    "units": 160.6323,
    "buy_nav": 179.2915,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 120503,
    "scheme_name": "Axis ELSS Tax Saver Fund - Direct Plan - Growth Option",
    "units": 1266.9601,
    "buy_nav": 86.822,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 120692,
    "scheme_name": "ICICI Prudential Corporate Bond Fund - Direct Plan - Growth",
    "units": 3354.649,
    "buy_nav": 26.8284,
    "buy_date": "2021-06-10",
    "notes": "Sample: SIP 2021-06-10 onwards",
    "profile_name": "Sample Portfolio"
  }
]

export const SAMPLE_REDEMPTIONS: Omit<Redemption, 'id' | 'created_at'>[] = [
  {
    "scheme_code": 125354,
    "scheme_name": "Axis Small Cap Fund - Direct Plan - Growth",
    "units": 233.1549,
    "sell_nav": 83.96,
    "sell_date": "2023-08-11",
    "notes": "Partial profit booking \u2014 smallcap peak",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 131373,
    "scheme_name": "Kotak Equity Savings Fund - Direct - Growth",
    "units": 489.0343,
    "sell_nav": 27.9742,
    "sell_date": "2024-12-13",
    "notes": "Partial rebalance \u2014 reduced conservative hybrid",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 140243,
    "scheme_name": "Edelweiss Greater China Equity Off-shore Fund - Direct Plan - Growth",
    "units": 57.4041,
    "sell_nav": 41.257,
    "sell_date": "2022-12-14",
    "notes": "Partial exit \u2014 China underperformance",
    "profile_name": "Sample Portfolio"
  },
  {
    "scheme_code": 120594,
    "scheme_name": "ICICI Prudential Technology Fund - Direct Plan - Growth",
    "units": 7.4725,
    "sell_nav": 165.77,
    "sell_date": "2022-01-28",
    "notes": "Partial exit \u2014 tech sector correction",
    "profile_name": "Sample Portfolio"
  }
]
